### ISSUE TITLE
Request to upload config files

### ISSUE THREAD

**Issue by byminji** [msight-tech/research-siamattn#1]
While I was trying to test the SiamAttn tracker as the inference guide on your GitHub page,
I found out that config files (config_otb100.yaml & config_vot2018.yaml) are missing on the page.
I tried to use the configs from the baseline PySot repository but failed since the network settings are too different.
Please upload the config files including layer settings and hyper-parameters.

**Comment by amirhamidihd** [comment]
I have this problem too, and because of mismatching configuration file I got runtime error while testing the code.
Please upload the config files including layer settings and hyper-parameters.
Thanks

**Comment by xiongyl** [comment]
The config files have been uploaded on [Google Drive](https://drive.google.com/drive/folders/1043coIpFniNeIMW8VH_wRax5PBMU4sTR). Thanks for pointing out.
